import {
  User,
  Victim,
  Counselor,
  Facility,
  Question,
  DailyCheckIn,
  Response,
  Conversation,
  ConversationMessage,
  VoiceSession,
  VoiceFeature,
  DistressAssessment,
  RiskEvent,
  Alert,
  CounselorAssignment,
  FollowUp,
  Referral,
  ClinicalNote,
  AuditLog,
  AdminConfig,
  SmsLog,
} from './types';
import bcrypt from 'bcryptjs';

// Pre-computed bcrypt hash for password "Password123!"
const defaultPasswordHash = bcrypt.hashSync('Password123!', 10);

export const initialFacilities: Facility[] = [
  {
    id: 'fac-1',
    name: 'Thanjavur Rural Primary Health Centre',
    type: 'Primary Health Centre (PHC)',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    contactPhone: '+91 4362 278100',
    address: 'Near Old Bus Stand, Thiruvaiyaru Road, Thanjavur, TN',
    hasPsychiatrist: false,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fac-2',
    name: 'Vidarbha District Hospital & Mental Health Wing',
    type: 'District Hospital',
    district: 'Yavatmal',
    state: 'Maharashtra',
    contactPhone: '+91 7232 244501',
    address: 'Civil Lines, Hospital Road, Yavatmal, MH',
    hasPsychiatrist: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fac-3',
    name: 'Wayanad Community Health Centre',
    type: 'Community Health Centre (CHC)',
    district: 'Wayanad',
    state: 'Kerala',
    contactPhone: '+91 4936 202344',
    address: 'Mananthavady Post, Wayanad, KL',
    hasPsychiatrist: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fac-4',
    name: 'Mandya Taluk Hospital & Tele-Counseling Unit',
    type: 'Sub-District Hospital',
    district: 'Mandya',
    state: 'Karnataka',
    contactPhone: '+91 8232 220045',
    address: 'Mysuru-Bengaluru Highway Road, Mandya, KA',
    hasPsychiatrist: false,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fac-5',
    name: 'Anantapur District Mental Health Centre',
    type: 'District Specialist Hospital',
    district: 'Anantapur',
    state: 'Andhra Pradesh',
    contactPhone: '+91 8554 275520',
    address: 'Court Road, Anantapur, AP',
    hasPsychiatrist: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialUsers: User[] = [
  // Administrators
  {
    id: 'usr-admin-1',
    email: 'admin@gramincare.in',
    phoneNumber: '+91 98000 00001',
    passwordHash: defaultPasswordHash,
    role: 'ADMIN',
    name: 'District Health Administrator',
    preferredLanguage: 'ENGLISH',
    isActive: true,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Counselors
  {
    id: 'usr-counselor-1',
    email: 'kavitha.sundaram@gramincare.in',
    phoneNumber: '+91 98401 23456',
    passwordHash: defaultPasswordHash,
    role: 'COUNSELOR',
    name: 'Dr. Kavitha Sundaram',
    preferredLanguage: 'TAMIL',
    isActive: true,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-counselor-2',
    email: 'amit.sharma@gramincare.in',
    phoneNumber: '+91 98230 56789',
    passwordHash: defaultPasswordHash,
    role: 'COUNSELOR',
    name: 'Dr. Amit Sharma',
    preferredLanguage: 'HINDI',
    isActive: true,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Victims
  {
    id: 'usr-victim-1',
    email: 'priya.lakshmi@ruralcare.org',
    phoneNumber: '+91 94432 11001',
    passwordHash: defaultPasswordHash,
    role: 'VICTIM',
    name: 'Priya Lakshmi',
    preferredLanguage: 'TAMIL',
    isActive: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-victim-2',
    email: 'ramesh.kumar@ruralcare.org',
    phoneNumber: '+91 98221 11002',
    passwordHash: defaultPasswordHash,
    role: 'VICTIM',
    name: 'Ramesh Kumar',
    preferredLanguage: 'HINDI',
    isActive: true,
    createdAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-victim-3',
    email: 'ananya.nair@ruralcare.org',
    phoneNumber: '+91 94950 11003',
    passwordHash: defaultPasswordHash,
    role: 'VICTIM',
    name: 'Ananya Nair',
    preferredLanguage: 'MALAYALAM',
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-victim-4',
    email: 'suresh.gowda@ruralcare.org',
    phoneNumber: '+91 98450 11004',
    passwordHash: defaultPasswordHash,
    role: 'VICTIM',
    name: 'Suresh Gowda',
    preferredLanguage: 'KANNADA',
    isActive: true,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-victim-5',
    email: 'rajesh.reddy@ruralcare.org',
    phoneNumber: '+91 94400 11005',
    passwordHash: defaultPasswordHash,
    role: 'VICTIM',
    name: 'Rajesh Reddy',
    preferredLanguage: 'TELUGU',
    isActive: true,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialCounselors: Counselor[] = [
  {
    id: 'cns-1',
    userId: 'usr-counselor-1',
    badgeNumber: 'CNS-TN-401',
    specialization: 'Senior Community Counselor & Crisis Triage',
    facilityId: 'fac-1',
    assignedDistrict: 'Thanjavur',
    isAvailable: true,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cns-2',
    userId: 'usr-counselor-2',
    badgeNumber: 'CNS-MH-108',
    specialization: 'District Mental Health Officer & Triage Specialist',
    facilityId: 'fac-2',
    assignedDistrict: 'Yavatmal',
    isAvailable: true,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialVictims: Victim[] = [
  {
    id: 'vic-1',
    userId: 'usr-victim-1',
    victimCode: 'V-1001',
    age: 34,
    gender: 'Female',
    village: 'Melattur Gramam',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    emergencyContactName: 'Murugan (Husband)',
    emergencyContactPhone: '+91 94432 99881',
    assignedCounselorId: 'cns-1',
    currentDistressScore: 38,
    currentRiskLevel: 'MILD',
    lastCheckInAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vic-2',
    userId: 'usr-victim-2',
    victimCode: 'V-1002',
    age: 42,
    gender: 'Male',
    village: 'Ralegaon Village',
    district: 'Yavatmal',
    state: 'Maharashtra',
    emergencyContactName: 'Sunita Kumar (Wife)',
    emergencyContactPhone: '+91 98221 77662',
    assignedCounselorId: 'cns-2',
    currentDistressScore: 81,
    currentRiskLevel: 'HIGH',
    lastCheckInAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 21 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vic-3',
    userId: 'usr-victim-3',
    victimCode: 'V-1003',
    age: 28,
    gender: 'Female',
    village: 'Meppadi Village',
    district: 'Wayanad',
    state: 'Kerala',
    emergencyContactName: 'Gopakumar (Father)',
    emergencyContactPhone: '+91 94950 44331',
    assignedCounselorId: 'cns-1',
    currentDistressScore: 18,
    currentRiskLevel: 'LOW',
    lastCheckInAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vic-4',
    userId: 'usr-victim-4',
    victimCode: 'V-1004',
    age: 50,
    gender: 'Male',
    village: 'Pandavapura Hobli',
    district: 'Mandya',
    state: 'Karnataka',
    emergencyContactName: 'Manjula (Wife)',
    emergencyContactPhone: '+91 98450 33221',
    assignedCounselorId: 'cns-1',
    currentDistressScore: 62,
    currentRiskLevel: 'ELEVATED',
    lastCheckInAt: new Date(Date.now() - 28 * 3600000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 28 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vic-5',
    userId: 'usr-victim-5',
    victimCode: 'V-1005',
    age: 39,
    gender: 'Male',
    village: 'Dharmavaram Rural',
    district: 'Anantapur',
    state: 'Andhra Pradesh',
    emergencyContactName: 'Lakshmi Devi (Sister)',
    emergencyContactPhone: '+91 94400 88992',
    assignedCounselorId: 'cns-2',
    currentDistressScore: 88,
    currentRiskLevel: 'HIGH',
    lastCheckInAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    lastInteractionAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialQuestions: Question[] = [
  {
    id: 'q-mood-1',
    code: 'Q_MOOD',
    category: 'mood',
    promptEnglish: 'How has your overall mood and peace of mind been today?',
    promptTamil: 'இன்று உங்கள் மனம் மற்றும் அமைதி எவ்வாறு உள்ளது?',
    promptHindi: 'आज आपका मन और मन की शांति कैसी रही?',
    promptTelugu: 'ఈ రోజు మీ మనస్సు మరియు శాంతి ఎలా ఉన్నాయి?',
    promptMalayalam: 'ഇന്ന് നിങ്ങളുടെ മനസ്സിന്റെ സമാധാനവും അവസ്ഥയും എങ്ങനെയുണ്ട്?',
    promptKannada: 'ಇಂದು ನಿಮ್ಮ ಮನಸ್ಸು ಮತ್ತು ಶಾಂತಿ ಹೇಗಿದೆ?',
    weight: 1.2,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'q-sleep-1',
    code: 'Q_SLEEP',
    category: 'sleep',
    promptEnglish: 'How was your sleep last night? Did you wake up feeling rested or disturbed?',
    promptTamil: 'நேற்று இரவு உங்கள் தூக்கம் எப்படி இருந்தது? அமைதியாக தூங்க முடிந்ததா?',
    promptHindi: 'कल रात आपकी नींद कैसी रही? क्या आप आराम महसूस कर रहे हैं?',
    promptTelugu: 'నిన్న రాత్రి మీ నిద్ర ఎలా ఉంది? విశ్రాంతిగా అనిపించిందా?',
    promptMalayalam: 'കഴിഞ്ഞ രാത്രി ഉറക്കം എങ്ങനെയുണ്ടായിരുന്നു? സുഖകരമായി ഉറങ്ങാൻ കഴിഞ്ഞോ?',
    promptKannada: 'ನಿನ್ನೆ ರಾತ್ರಿ ನಿಮ್ಮ ನಿದ್ದೆ ಹೇಗಿತ್ತು? ನೆಮ್ಮದಿಯ ನಿದ್ದೆ ಆಯಿತಾ?',
    weight: 1.1,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'q-stress-1',
    code: 'Q_STRESS',
    category: 'stress',
    promptEnglish: 'Have you been feeling overwhelmed by family or agricultural/work burdens today?',
    promptTamil: 'குடும்ப அல்லது வேலை சுமையால் இன்று அதிக மன அழுத்தம் உணர்ந்தீர்களா?',
    promptHindi: 'क्या आपको आज पारिवारिक या कामकाज के तनाव का भारीपन महसूस हुआ?',
    promptTelugu: 'కుటుంబ లేదా పని భారం వల్ల ఈ రోజు ఒత్తిడికి గురయ్యారా?',
    promptMalayalam: 'കുടുംബ അല്ലെങ്കിൽ തൊഴിൽ സമ്മർദ്ദം ഇന്ന് അധികമായി തോന്നിയോ?',
    promptKannada: 'ಕುಟುಂಬ ಅಥವಾ ಕೆಲಸದ ಒತ್ತಡದಿಂದ ಇಂದು ಹೆಚ್ಚು ದಣಿವು ಅನಿಸಿತಾ?',
    weight: 1.3,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'q-social-1',
    code: 'Q_SOCIAL',
    category: 'social',
    promptEnglish: 'Were you able to talk or share your feelings with anyone you trust today?',
    promptTamil: 'இன்று நீங்கள் நம்பும் எவருடனும் உங்கள் உணர்வுகளைப் பகிர்ந்து கொள்ள முடிந்ததா?',
    promptHindi: 'क्या आज आप अपने किसी करीबी या भरोसेमंद व्यक्ति से बातचीत कर पाए?',
    promptTelugu: 'ఈ రోజు మీకు నమ్మకమైన వారితో మాట్లాడటానికి అవకాశం వచ్చిందా?',
    promptMalayalam: 'ഇന്ന് നിങ്ങൾ വിശ്വസിക്കുന്ന ആരോടെങ്കിലും സംസാരിക്കാൻ സാധിച്ചോ?',
    promptKannada: 'ಇಂದು ನೀವು ನಂಬುವ ಯಾರೊಂದಿಗಾದರೂ ಮಾತನಾಡಲು ಸಾಧ್ಯವಾಯಿತಾ?',
    weight: 0.9,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'q-functioning-1',
    code: 'Q_FUNCTIONING',
    category: 'functioning',
    promptEnglish: 'Were you able to carry out your daily routines and meals with ease?',
    promptTamil: 'இன்றைய அன்றாட பணிகளையும் உணவையும் வழக்கம்போல் செய்ய முடிந்ததா?',
    promptHindi: 'क्या आप आज के दैनिक कार्य और भोजन सामान्य रूप से कर पाए?',
    promptTelugu: 'ఈ రోజు రోజువారీ పనులు మరియు భోజనం సాధారణంగా చేసుకోగలిగారా?',
    promptMalayalam: 'ദൈനംദിന കാര്യങ്ങളും ഭക്ഷണവും പതിവുപോലെ ചെയ്യാൻ സാധിച്ചോ?',
    promptKannada: 'ದೈನಂದಿನ ಕೆಲಸಗಳು ಮತ್ತು ಊಟವನ್ನು ಸರಾಗವಾಗಿ ಮಾಡಲು ಸಾಧ್ಯವಾಯಿತಾ?',
    weight: 1.0,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
];

export const initialAssessments: DistressAssessment[] = [
  {
    id: 'ast-1',
    victimId: 'vic-1',
    score: 38,
    previousScore: 42,
    trend: 'DECREASING',
    riskLevel: 'MILD',
    confidence: 'Moderate',
    reason: 'Reported mild fatigue and seasonal agricultural stress, but sleep and social connection are stable.',
    contributingFactors: ['Agricultural work stress', 'Mild physical tiredness', 'Stable family support'],
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'ast-2',
    victimId: 'vic-2',
    score: 81,
    previousScore: 55,
    trend: 'INCREASING',
    riskLevel: 'HIGH',
    confidence: 'High',
    reason: 'Significant spike in distress due to severe crop debt stress and 3 consecutive nights of severe insomnia.',
    contributingFactors: ['Crop loan repayment anxiety', 'Severe insomnia (<3 hrs sleep)', 'Feelings of heavy burden', 'Social withdrawal'],
    createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
  {
    id: 'ast-3',
    victimId: 'vic-3',
    score: 18,
    previousScore: 22,
    trend: 'DECREASING',
    riskLevel: 'LOW',
    confidence: 'High',
    reason: 'Healthy mood, positive emotional outlook, regular sleep schedule, actively engaging in local SHG craft work.',
    contributingFactors: ['Good sleep hygiene', 'Strong family communication', 'Engaged in community routine'],
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 'ast-4',
    victimId: 'vic-4',
    score: 62,
    previousScore: 52,
    trend: 'INCREASING',
    riskLevel: 'ELEVATED',
    confidence: 'Moderate',
    reason: 'Elevated stress indicators with missed check-in yesterday and persistent headaches reported.',
    contributingFactors: ['Persistent physical exhaustion', 'Missed check-in', 'Difficulty concentrating'],
    createdAt: new Date(Date.now() - 28 * 3600000).toISOString(),
  },
  {
    id: 'ast-5',
    victimId: 'vic-5',
    score: 88,
    previousScore: 68,
    trend: 'INCREASING',
    riskLevel: 'HIGH',
    confidence: 'High',
    reason: 'High distress signals detected during conversational check-in. Safety escalation triggered with counselor notification.',
    contributingFactors: ['Expressed deep hopelessness', 'Refusing meals', 'Acute family conflict', 'High emotional volatility'],
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
];

export const initialAlerts: Alert[] = [
  {
    id: 'alt-1',
    victimId: 'vic-2',
    assessmentId: 'ast-2',
    counselorId: 'cns-2',
    priority: 'HIGH',
    status: 'PENDING',
    title: 'High Distress Spike & Insomnia: Ramesh Kumar (V-1002)',
    currentScore: 81,
    previousScore: 55,
    trend: 'Increasing (+26 pts)',
    signals: [
      'Significant increase in reported distress (+26 pts in 48h)',
      'Severe sleep disruption (<3 hours for 3 nights)',
      'Reported debt-related anxiety affecting daily routine',
      'Expressed feelings of isolation in village'
    ],
    recommendedAction: 'Immediate counselor phone call review & local ASHA worker visit verification',
    acknowledgedAt: null,
    resolvedAt: null,
    resolutionNotes: null,
    createdAt: new Date(Date.now() - 17 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 17 * 3600000).toISOString(),
  },
  {
    id: 'alt-2',
    victimId: 'vic-5',
    assessmentId: 'ast-5',
    counselorId: 'cns-2',
    priority: 'HIGH',
    status: 'ACKNOWLEDGED',
    title: 'Urgent Safety Escalation: Rajesh Reddy (V-1005)',
    currentScore: 88,
    previousScore: 68,
    trend: 'Increasing (+20 pts)',
    signals: [
      'High distress verbal statements in check-in conversation',
      'Expressed intense hopelessness regarding family dispute',
      'Refusal of food and essential tasks for 2 days',
      'Emergency helpline guidance provided in app'
    ],
    recommendedAction: 'In-person PHC Medical Officer referral & family liaison outreach',
    acknowledgedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    resolvedAt: null,
    resolutionNotes: 'Dr. Amit Sharma acknowledged alert. Tele-MANAS hotline coordinated with local PHC.',
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'alt-3',
    victimId: 'vic-4',
    assessmentId: 'ast-4',
    counselorId: 'cns-1',
    priority: 'ELEVATED',
    status: 'PENDING',
    title: 'Elevated Distress & Missed Check-in: Suresh Gowda (V-1004)',
    currentScore: 62,
    previousScore: 52,
    trend: 'Increasing (+10 pts)',
    signals: [
      'Distress elevated to 62/100',
      'Check-in missed yesterday (SMS reminder sent)',
      'Reported chronic physical fatigue'
    ],
    recommendedAction: 'Schedule weekly support follow-up call within 24 hours',
    acknowledgedAt: null,
    resolvedAt: null,
    resolutionNotes: null,
    createdAt: new Date(Date.now() - 27 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 27 * 3600000).toISOString(),
  },
];

export const initialFollowUps: FollowUp[] = [
  {
    id: 'flw-1',
    victimId: 'vic-2',
    counselorId: 'cns-2',
    dueDate: new Date(Date.now() + 18 * 3600000).toISOString(), // Tomorrow morning
    status: 'PENDING',
    priority: 'HIGH',
    notes: 'Urgent check on sleep quality, debt coping resources, and connection with local Krishi Vigyan Kendra counseling.',
    outcomeNotes: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 16 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 16 * 3600000).toISOString(),
  },
  {
    id: 'flw-2',
    victimId: 'vic-5',
    counselorId: 'cns-2',
    dueDate: new Date(Date.now() + 6 * 3600000).toISOString(), // Today afternoon
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    notes: 'Emergency liaison with sister (Lakshmi Devi) and verification of PHC Doctor appointment.',
    outcomeNotes: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'flw-3',
    victimId: 'vic-1',
    counselorId: 'cns-1',
    dueDate: new Date(Date.now() + 72 * 3600000).toISOString(), // In 3 days
    status: 'PENDING',
    priority: 'MILD',
    notes: 'Routine bi-weekly supportive check-in. Review relaxation breathing exercises.',
    outcomeNotes: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'flw-4',
    victimId: 'vic-4',
    counselorId: 'cns-1',
    dueDate: new Date(Date.now() - 6 * 3600000).toISOString(), // Overdue by 6 hours
    status: 'PENDING',
    priority: 'ELEVATED',
    notes: 'Follow-up regarding missed check-in and migraine complaints.',
    outcomeNotes: null,
    completedAt: null,
    createdAt: new Date(Date.now() - 30 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialReferrals: Referral[] = [
  {
    id: 'ref-1',
    victimId: 'vic-5',
    counselorId: 'cns-2',
    facilityId: 'fac-5',
    reason: 'Emergency psychiatric clinical evaluation & crisis care plan due to severe distress escalation',
    status: 'IN_PROGRESS',
    notes: 'Referred directly by Dr. Amit Sharma. Tele-MANAS reference #TM-AP-2026-9912.',
    appointmentDate: new Date(Date.now() + 24 * 3600000).toISOString(),
    completedAt: null,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'ref-2',
    victimId: 'vic-2',
    counselorId: 'cns-2',
    facilityId: 'fac-2',
    reason: 'Chronic insomnia and somatic distress assessment with Medical Officer',
    status: 'CREATED',
    notes: 'Scheduled for in-person consultation with visiting psychiatrist on Friday.',
    appointmentDate: new Date(Date.now() + 48 * 3600000).toISOString(),
    completedAt: null,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ref-3',
    victimId: 'vic-1',
    counselorId: 'cns-1',
    facilityId: 'fac-1',
    reason: 'Routine community maternal & mental health support session at local PHC',
    status: 'COMPLETED',
    notes: 'Attended session on 18th. Reported feeling lighter after group breathing session.',
    appointmentDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    completedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

export const initialClinicalNotes: ClinicalNote[] = [
  {
    id: 'note-1',
    counselorId: 'cns-1',
    victimId: 'vic-1',
    content: 'Patient Priya Lakshmi demonstrates good emotional insight. Coping mechanisms for seasonal workload are improving. Advised continued 5-minute diaphragmatic breathing before sleep.',
    isPrivate: true,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'note-2',
    counselorId: 'cns-2',
    victimId: 'vic-2',
    content: 'Patient Ramesh Kumar is under acute economic pressure. High risk of decompensation if sleep continues to fail. Coordinated with Gram Sevak for institutional debt counseling. Need close monitoring.',
    isPrivate: true,
    createdAt: new Date(Date.now() - 16 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 16 * 3600000).toISOString(),
  },
];

export const initialConversations: Conversation[] = [
  {
    id: 'conv-1',
    victimId: 'vic-1',
    title: 'Daily Evening Supportive Chat',
    language: 'TAMIL',
    isArchived: false,
    summary: 'Patient shared feeling tired after harvesting. Received supportive relaxation advice and encouragement to rest.',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];

export const initialMessages: ConversationMessage[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    sender: 'AI',
    content: 'வணக்கம் பிரியா அவர்களே 👋 இன்று உங்கள் நாள் எவ்வாறு இருந்தது? ஏதேனும் சிரமம் உள்ளதா?',
    language: 'TAMIL',
    distressScore: 0,
    safetyFlag: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    sender: 'USER',
    content: 'இன்று வயல் வேலை அதிகம் இருந்தது. உடல் மிகவும் களைப்பாக உள்ளது, ஆனால் குடும்பத்துடன் அமைதியாக இருக்கிறேன்.',
    language: 'TAMIL',
    distressScore: 28,
    safetyFlag: false,
    createdAt: new Date(Date.now() - 110 * 60000).toISOString(),
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    sender: 'AI',
    content: 'உங்கள் கடின உழைப்பு புரிகிறது பிரியா. உடலுக்கு ஓய்வு மிகவும் முக்கியம். வெதுவெதுப்பான நீர் குடித்துவிட்டு, ஆழ்ந்த மூச்சுப் பயிற்சி செய்துவிட்டு தூங்க முயற்சிக்கவும். நீங்கள் நலம் பெற வேண்டுகிறேன்.',
    language: 'TAMIL',
    distressScore: 15,
    safetyFlag: false,
    createdAt: new Date(Date.now() - 105 * 60000).toISOString(),
  },
];

export const initialVoiceFeatures: VoiceFeature[] = [
  {
    id: 'vf-1',
    voiceSessionId: 'vs-1',
    speechRate: 110, // slightly slower than average 140
    pauseFrequency: 8.5,
    pitchVariation: 12.4,
    energyLevel: 0.45,
    voiceStability: 74,
    acousticSignal: 'MILD',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'vf-2',
    voiceSessionId: 'vs-2',
    speechRate: 85, // marked slowing
    pauseFrequency: 14.2,
    pitchVariation: 6.8, // flat intonation
    energyLevel: 0.22, // low energy
    voiceStability: 48,
    acousticSignal: 'HIGH',
    createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
];

export const initialVoiceSessions: VoiceSession[] = [
  {
    id: 'vs-1',
    victimId: 'vic-1',
    durationSec: 45,
    language: 'TAMIL',
    audioUri: null,
    transcript: 'இன்று கொஞ்சம் சோர்வாக உள்ளது. தூக்கம் சரியாக வரவில்லை.',
    summary: 'Spoken reflection in Tamil indicating mild tiredness and slight sleep disturbance.',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'vs-2',
    victimId: 'vic-2',
    durationSec: 72,
    language: 'HINDI',
    audioUri: null,
    transcript: 'मुझे बहुत चिंता हो रही है। फसल का नुकसान और कर्ज का दबाव सहा नहीं जा रहा।',
    summary: 'Spoken distress expressing high anxiety regarding crop debt and feeling overwhelmed.',
    createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-counselor-1',
    action: 'LOGIN',
    resourceType: 'User',
    resourceId: 'usr-counselor-1',
    details: JSON.stringify({ method: 'PASSWORD', role: 'COUNSELOR', badge: 'CNS-TN-401' }),
    ipAddress: '10.0.4.12',
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: 'aud-2',
    userId: 'usr-victim-5',
    action: 'EMERGENCY_ESCALATION_TRIGGERED',
    resourceType: 'Alert',
    resourceId: 'alt-2',
    details: JSON.stringify({ victimCode: 'V-1005', score: 88, reason: 'High distress signals detected' }),
    ipAddress: '10.0.7.88',
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'aud-3',
    userId: 'usr-counselor-2',
    action: 'ALERT_ACKNOWLEDGED',
    resourceType: 'Alert',
    resourceId: 'alt-2',
    details: JSON.stringify({ counselorBadge: 'CNS-MH-108', alertId: 'alt-2' }),
    ipAddress: '10.0.5.21',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'aud-4',
    userId: 'usr-counselor-2',
    action: 'REFERRAL_CREATED',
    resourceType: 'Referral',
    resourceId: 'ref-1',
    details: JSON.stringify({ victimCode: 'V-1005', facility: 'Anantapur District Mental Health Centre' }),
    ipAddress: '10.0.5.21',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
];

export const initialSmsLogs: SmsLog[] = [
  {
    id: 'sms-1',
    victimId: 'vic-4',
    recipientPhone: '+91 98450 11004',
    message: 'Hello Suresh. Your daily wellbeing check-in is available. Please open your Aarva Health Care app when convenient.',
    purpose: 'CHECKIN_REMINDER',
    status: 'DELIVERED',
    providerMessageId: 'SM-TW-8891230491',
    sentAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'sms-2',
    victimId: 'vic-2',
    recipientPhone: '+91 98221 11002',
    message: 'Hello Ramesh. Your daily wellbeing check-in is available. Please open your Aarva Health Care app when convenient.',
    purpose: 'CHECKIN_REMINDER',
    status: 'DELIVERED',
    providerMessageId: 'SM-TW-8891230492',
    sentAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];

export const initialAdminConfig: AdminConfig = {
  id: 'default',
  distressThresholdLow: 24.0,
  distressThresholdMild: 49.0,
  distressThresholdElev: 74.0,
  distressThresholdHigh: 100.0,
  dailyReminderHourUtc: 4, // 9:30 AM IST
  twilioEnabled: false,
  smsGatewayEnabled: true,
  autoEscalateHighRisk: true,
  emergencyHotlines: [
    {
      name: 'Tele-MANAS National Tele Mental Health Helpline',
      number: '14416',
      description: '24/7 Free Multilingual Mental Health & Psychological Support (Govt. of India)',
      tollFree: true,
    },
    {
      name: 'KIRAN Mental Health Rehabilitation Helpline',
      number: '1800-599-0019',
      description: 'Dep. of Empowerment of Persons with Disabilities, Govt of India (13 languages)',
      tollFree: true,
    },
    {
      name: 'National Emergency Response Support System',
      number: '112',
      description: 'All-in-one Emergency Police, Ambulance and Disaster helpline',
      tollFree: true,
    },
    {
      name: 'Vandrevala Foundation Helpline',
      number: '+91 9999 666 555',
      description: '24/7 Crisis & Mental Wellbeing Support',
      tollFree: false,
    },
  ],
  updatedAt: new Date().toISOString(),
};
